schemaVersion: 2.1.0
metadata:
  name: quarkus-api-example-demo
components:
  - name: tools
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-latest
      memoryLimit: 6G
      cpuLimit: 1500m
      endpoints:
        - name: http-quarkus
          targetPort: 8080
        - exposure: none
          name: debug
          targetPort: 5005
  - name: postgresql
    container:
      image: 'quay.io/centos7/postgresql-13-centos7@sha256:994f5c622e2913bda1c4a7fa3b0c7e7f75e7caa3ac66ff1ed70ccfe65c40dd75'
      env:
        - name: POSTGRESQL_USER
          value: user
        - name: POSTGRESQL_PASSWORD
          value: password
        - name: POSTGRESQL_DATABASE
          value: food_db
        - name: PGDATA
          value: /tmp/pgdata
commands:
  - id: dev-run
    exec:
      component: tools
      commandLine: 'mvn quarkus:dev -Dquarkus.http.host=0.0.0.0'
      hotReloadCapable: true
      group:
        kind: run
        isDefault: true
      workingDir: ${PROJECT_SOURCE}
