schemaVersion: 2.2.0
metadata:
  name: quarkus-api-example-demo
components:
  - name: tools
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-latest
      memoryLimit: 4G
      cpuLimit: '1'
